site_name: LibCanComm User Manual
site_description: User Manual for LibCanComm, the library for convenient access to CAN communication, based on the SocketCAN kernel functionality.
repo_url: https://github.com/pragmaticlinuxblog/libcancomm
nav:
  - Getting started: 'index.md'
  - API reference: 'api.md'
  - Example: 'example.md'
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate
    - navigation.top
    - navigation.tabs
  palette: 
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: blue
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pragmaticlinux
      name: PragmaticLinux on Twitter
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/pragmaticlinux
      name: PragmaticLinux on Pinterest
    - icon: fontawesome/brands/github
      link: https://github.com/pragmaticlinuxblog
      name: PragmaticLinux on GitHub
copyright: Copyright &copy; 2022 by PragmaticLinux
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
